{% set name = "elpigraph-python" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9b054201c9557c9a5c12db2218ea8948f0f3575af783b65ac9c054457e6875a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.16.2
    - pandas >=0.23.4
    - numba >=0.49.1 
    - scikit-learn >=0.21.3
    - scipy >=1.2.0
    - python-igraph >=0.7.1
    - matplotlib-base


test:
  imports:
    - elpigraph
    - elpigraph.src
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/j-bac/elpigraph-python
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Elastic Principal Graphs algorithm (ElPiGraph) for Python'

  description: |
    elpigraph-python is a package implementing the Elastic Principal Graphs algorithm for manifold learning.
  doc_url: https://elpigraph-python.readthedocs.io/
  dev_url: https://github.com/elpigraph-python/elpigraph/

extra:
  recipe-maintainers:
    - j-bac
    - auranic
